name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and start services
      run: docker-compose -f docker-compose.yml up --build -d

    - name: Wait for services to be ready
      run: |
        while ! curl -s http://localhost:4566; do sleep 1; done
        while ! curl -s http://localhost:8000; do sleep 1; done

    - name: Run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    - name: Shut down services
      run: docker-compose down
