name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Compose
      run: |
        mkdir -p $HOME/bin
        curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/bin/docker-compose
        chmod +x $HOME/bin/docker-compose
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and start services
      run: docker-compose -f docker-compose.yml up --build -d

    - name: Install awscli-local
      run: pip install awscli-local

    - name: Wait for Localstack to be ready
      run: |
        until awslocal s3 ls > /dev/null 2>&1; do
          echo "Waiting for Localstack S3 service to be ready..."
          sleep 5
        done

    - name: Wait for Flask app to be ready
      run: |
        until curl -s http://localhost:8000/items | grep "[]" > /dev/null; do
          echo "Waiting for Flask app to be ready..."
          sleep 5
        done

    - name: Run tests
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    - name: Shut down services
      run: docker-compose down
