name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install Docker Compose
        run: |
          mkdir -p $HOME/bin
          curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o $HOME/bin/docker-compose
          chmod +x $HOME/bin/docker-compose
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install awscli-local
        run: pip install awscli-local

      - name: Install dockerize
        run: |
          curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar -C /usr/local/bin -xzv

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start services
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Wait for services to start
        run: dockerize -wait tcp://localhost:8000 -timeout 1m

      - name: Run tests
        run: docker-compose exec app python -m pytest

      - name: Shut down services
        run: docker-compose down
